FROM node:22-alpine

WORKDIR /opt/manage

COPY ./node_modules /opt/manage/node_modules
COPY ./src /opt/manage/src
COPY package.json /opt/manage/package.json
COPY . /opt/manage/

#RUN rm package-lock.json

RUN npm install
#RUN npm update

EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]

